added if statement to check current branch, also fixed email config

diff --git a/.github/workflows/download_words.yaml b/.github/workflows/download_words.yaml
--- a/.github/workflows/download_words.yaml
+++ b/.github/workflows/download_words.yaml
@@ -25,6 +25,14 @@ jobs:
         run: |
           git fetch origin
           git checkout $NEW_BRANCH
+
+          CURRENT_BRANCH=$(git branch --show-current)
+          
+          if [ "$CURRENT_BRANCH" != $NEW_BRANCH ]; then
+            echo "Error: expected $NEW_BRANCH, but currently on $CURRENT_BRANCH"
+            exit 1
+          fi    
+
           git reset --hard origin/main
           git push --force-with-lease origin $NEW_BRANCH
       
@@ -39,7 +47,7 @@ jobs:
       - name: commit
         run: |
           git config user.name ${{github.actor}}
-          git config user.email ${{github.actor}}
+          git config user.email ${{github.actor}}@users.noreply.github.com"
 
           git add words.csv
           git commit -m "Automatic update of words.csv"
